spring.application.name=backend

spring.datasource.url=jdbc:postgresql://dpg-d8pa4amrnols73f9na8g-a.oregon-postgres.render.com:5432/mth_tyo3
spring.datasource.username=mth_tyo3_user
spring.datasource.password=hOAOJtxJ3431NPcBFeyeicvTh5njOWGo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081